#! /bin/sh

# Copyright (c) 2026 Slawomir Wojciech Wojtczak (vermaden)
# All rights reserved.
#
# THIS SOFTWARE USES FREEBSD LICENSE (ALSO KNOWN AS 2-CLAUSE BSD LICENSE)
# https://freebsd.org/copyright/freebsd-license.html
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that following conditions are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS 'AS IS' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# ------------------------------
# UNATTENDED VM(s) IMAGE BUILDER
# ------------------------------
# vermaden [AT] interia [DOT] pl
# https://vermaden.wordpress.com

# DEFAULTS
ARG_MODE=${ARG_MODE:-"fetch:build:setup"}
ARG_FILE=${ARG_FILE:-"VERIMG"}
ARG_SIZE=${ARG_SIZE:-"10g"}
ARG_VERS=${ARG_VERS:-"releng/15.0"}
ARG_INST=${ARG_INST:-"beadm:lsblk"}
ARG_MNTD=${ARG_MNTD:-"/mnt"}
ARG_KERN=${ARG_KERN:-"GENERIC"}
ARG_SRCD=${ARG_SRCD:-"/usr/src"}
ARG_TYPE=${ARG_TYPE:-"img"}
ARG_REPO=${ARG_REPO:-"/usr/obj/usr/src/repo/FreeBSD:15:$( uname -m )/latest"}
ARG_POOL=${ARG_POOL:-"sys"}
ARG_BRCH=${ARG_BRCH:-"latest"}

# pkg(8) KEYS
PKG_NME="pkg.freebsd.org.2013102301"
PKG_KEY="b0170035af3acc5f3f3ae1859dc717101b4e6c1d0a794ad554928ca0cbb2f438"
BCK_NME="backup-signing-15"
BCK_KEY="56a77bdcb6c3cf7984729c6138bd5617c24aa0d466b3b604c96205b2c5629f3c"
AWS_NME="awskms-15"
AWS_KEY="1d7b45d20fa8d6ed26f9b4a13ac81a6b5df860b9fe644d07b87e92298ba72595"

# TRAP FUNCTION TO CLEANUP (begin)
__verimg_clean() {

  # UNMOUNT devfs(5) FILESYSTEM FROM CHROOT
  umount -f "${ARG_MNTD}/dev" 2> /dev/null

  # EXPORT CREATE ZFS POOL
  if zpool list ${ARG_POOL} 1> /dev/null 2> /dev/null
  then
    zpool export -f ${ARG_POOL} 2> /dev/null
  fi

  # UNMAPE FILE FROM md(4) NODE
  if [ "${DEVICE}" != "" ]
  then
    mdconfig -d -u /dev/${DEVICE} 2> /dev/null
  fi

  # CHECK IF DISK IMAGE IS ALREADY MAPPED WITH md(4) DRIVER ON OTHER PLACES
  ARG_FILE_PATH="$( pwd )/${ARG_FILE}"
  mdconfig -l -v 2> /dev/null \
    | while read NAME TYPE SIZE FILENAME GARBAGE
      do

        if [ "${ARG_FILE_PATH}" = "${FILENAME}" ]
        then
          mdconfig -d -u /dev/${NAME} 2> /dev/null
        fi

      done
  }
# TRAP FUNCTION TO CLEANUP (end)

# CLEAN IN BETWEEN AND AFTER
trap __verimg_clean SIGINT SIGQUIT SIGHUP SIGTRAP SIGABRT SIGTERM

# FUNCTION TO DISPLAY HELP (begin)
__usage() {
  NAME="${0##*/}"
  echo "usage:"
  echo "  ${NAME}: [OPTION(s)]"
  echo
  echo "options:"
  echo "  -f FILE  which file to use for VM image (default: VERIMG)"
  echo "  -s SIZE  size of VM image (default: 10g)"
  echo "  -r VERS  which FreeBSD version to use (default: releng/15.0)"
  echo "  -i LIST  colon (:) separated packages list to install (default: beadm:lsblk)"
  echo "  -m MNTD  mount directory for installation (default: /mnt)"
  echo "  -S SRCD  directory for FreeBSD source (default: /usr/src)"
  echo "  -p POOL  specify ZFS pool name (default: sys)"
  echo "  -b BRCH  specify branch for pkg(8) (default: latest)"
  echo "  -n       display options and exit"
  echo "  -k LIST  list of kernel configs to build in CONF1:CONF2:CONF3 format"
  echo "           if unspecified then only the GENERIC kernel will be built"
  echo "  -t TYPE  type of operation is one of options:"
  echo "           = img"
  echo "             - create FILE backend and do setup there (default)"
  echo "           = mnt"
  echo "             - do not use FILE backend and just setup at mount dir"
  echo "  -R REPO  dir where PKGBASE packages are located"
  echo "           (default: /usr/obj/usr/src/repo/FreeBSD:15:amd64/latest)"
  echo "  -M MODE  mode in which '${NAME}' to start:"
  echo "           = fetch:build:setup (default)"
  echo "             - fetch FreeBSD sources with git(1) clone into /usr/src"
  echo "             - build FreeBSD from sources from /usr/src in /usr/obj"
  echo "             - setup FreeBSD from /usr/obj PKGBASE repository"
  echo "           = build:setup"
  echo "             - build FreeBSD from sources from /usr/src in /usr/obj"
  echo "             - setup FreeBSD from /usr/obj PKGBASE repository"
  echo "           = setup"
  echo "             - setup FreeBSD from /usr/obj PKGBASE repository"
  echo
  echo "examples:"
  echo "  # verimg.sh -n -M setup -s 20g -r releng/15.0 -i lsblk:beadm:python:ansible"
  echo "  INFO: options that will be used                          "
  echo "    ARG_MODE: setup                                        "
  echo "    ARG_TYPE: img                                          "
  echo "    ARG_FILE: VERIMG                                       "
  echo "    ARG_SIZE: 20g                                          "
  echo "    ARG_VERS: releng/15.0                                  "
  echo "    ARG_INST: beadm:lsblk:python:ansible                   "
  echo "    ARG_MNTD: /mnt                                         "
  echo "    ARG_SRCD: /usr/src                                     "
  echo "    ARG_KERN: GENERIC                                      "
  echo "    ARG_POOL: sys                                          "
  echo "    ARG_REPO: /usr/obj/usr/src/repo/FreeBSD:15:amd64/latest"
  echo "    ARG_BRCH: latest                                       "
  echo
  echo "cleanup:"
  echo "  ${NAME}(8) takes care to clean up (unmount/export/...) after job is done/fail"
  echo "  but if for some reason it does not clean up properly - use this manual way"
  echo "    # umount -f ${ARG_MNTD}/dev"
  echo "    # zpool export -f ${ARG_POOL}"
  echo "    # mdconfig -d -u /dev/md0"
  echo
  echo "  md(4) device may be other then /dev/md0 so check with mdconfig(8) command"
  echo "    # mdconfig -l -v"
  echo "    md0     vnode      10G  /home/vermaden/VERIMG   -"
  echo
  exit 1
  }
# FUNCTION TO DISPLAY HELP (end)

# FUNCTION TO DISPLAY MESSAGE BEFORE COMMAND (begin)
__m() {
  echo
  echo "# ${@}"
  }
# FUNCTION TO DISPLAY MESSAGE BEFORE COMMAND (end)

# FUNCTION TO FETCH FreeBSD SOURCE (begin)
__verimg_fetch() {
  # CHECK git(1) IS INSTALLED
  __m "which git(1)"
  unalias    git 1> /dev/null 2> /dev/null
  if ! which git 1> /dev/null 2> /dev/null
  then
    echo "NOPE: install 'devel/git' package"
    __verimg_clean
    exit 1
  fi

  # FETCH FreeBSD SOURCES INTO ${ARG_SRCD} DIR
  __m "git clone -b '${ARG_VERS}' --depth 1 https://git.freebsd.org/src.git ${ARG_SRCD}"
  if ! git clone -b "${ARG_VERS}" --depth 1 https://git.freebsd.org/src.git ${ARG_SRCD} 2> /dev/null
  then
    echo "NOPE: can not fetch FreeBSD '${ARG_VERS}' source into '${ARG_SRCD}' dir"
    __verimg_clean
    exit 1
  fi

  }
# FUNCTION TO FETCH FreeBSD SOURCE (end)

# FUNCTION TO BUILD FreeBSD (begin)
__verimg_build() {

  __m "cd ${ARG_SRCD}"
  if ! cd ${ARG_SRCD} 2> /dev/null
  then
    echo "NOPE: can not cd(1) into '${ARG_SRCD}' dir."
    __verimg_clean
    exit 1
  fi

  # CHECK ALL '${ARG_KERN}' KERNEL CONFIG FILES EXIST
  KERNCONF=$( echo ${ARG_KERN} | tr ':' ' ' )
  ARCH=$( uname -m )
  for CONFIG in ${KERNCONF}
  do
    if [ ! -f ${ARG_SRCD}/sys/${ARCH}/conf/${CONFIG}
    then
      echo "NOPE: kernel config file '${CONFIG}' does not exists"
      __verimg_clean
      exit 1
    fi
  done

  # BUILD FREEBSD USERSPACE/KERNEL AND PKGBASE PACKAGES
  __m "make -j $( nproc --ignore=1 ) buildworld buildkernel KERNCONF='${KERNCONF}' update-packages KERNCONF='${KERNCONF}'"
  if ! make -j $( nproc --ignore=1 ) buildworld buildkernel KERNCONF="${KERNCONF}" update-packages KERNCONF="${KERNCONF}" 2> /dev/null
  then
    echo "NOPE: can not build FreeBSD from '${ARG_SRCD}' source"
    __verimg_clean
    exit 1
  fi

  }
# FUNCTION TO BUILD FreeBSD (end)

# FUNCTION TO SETUP FreeBSD (begin)
__verimg_setup() {

  # CHANGE CURRENT DIR INTO REPO DIR
  __m "cd "${ARG_REPO}""
  if ! cd "${ARG_REPO}" 2> /dev/null
  then
    echo "NOPE: can not cd(1) into '${ARG_REPO}' dir"
    __verimg_clean
    exit 1
  fi

  # CREATE pkg(8) REPO INSIDE THAT DIR
  __m "pkg repo ."
  if ! pkg repo . 2> /dev/null
  then
    echo "NOPE: can not create pkg-repo(8) in '${ARG_REPO}' dir"
    __verimg_clean
    exit 1
  fi

  # CREATE repos DIR
  __m "mkdir -p /usr/obj/repos"
  if ! mkdir -p /usr/obj/repos 2> /dev/null
  then
    echo "NOPE: can not create '/usr/obj/repos' dir"
    __verimg_clean
    exit 1
  fi

  # CREATE pkg-repo(8) REPOSITORY CONFIG
  __m "cat << EOF > /usr/obj/repos/FreeBSD-base.conf (...)"
  if ! cat << EOF > /usr/obj/repos/FreeBSD-base.conf 2> /dev/null
FreeBSD-base: {
  url: "file://${ARG_REPO}",
  enabled: yes
}
EOF
  then
    echo "NOPE: can not create /usr/obj/repos/FreeBSD-base.conf config"
    __verimg_clean
    exit 1
  fi

  # CREATE pkg(8) KEYS DIRS
  __m "mkdir -p ${ARG_MNTD}/usr/share/keys (...)"
  if ! mkdir -p \
         "${ARG_MNTD}/usr/share/keys/pkg/trusted"        \
         "${ARG_MNTD}/usr/share/keys/pkg/revoked"        \
         "${ARG_MNTD}/usr/share/keys/pkgbase-15/trusted" \
         "${ARG_MNTD}/usr/share/keys/pkgbase-15/revoked" 2> /dev/null
  then
    echo "NOPE: can not create pkg(8) keys dirs"
    __verimg_clean
    exit 1
  fi

  # CREATE pkg(8) KEYS 1/3
  __m "cat << EOF > ${ARG_MNTD}/usr/share/keys/pkg/trusted/${PKG_NME} (...)"
  cat << EOF > "${ARG_MNTD}/usr/share/keys/pkg/trusted/${PKG_NME}"
function: "sha256"
fingerprint: "${PKG_KEY}"
EOF

  # CREATE pkg(8) KEYS 2/3
  __m "cat << EOF > ${ARG_MNTD}/usr/share/keys/pkgbase-15/trusted/${BCK_NME} (...)"
  cat << EOF > "${ARG_MNTD}/usr/share/keys/pkgbase-15/trusted/${BCK_NME}"
function: "sha256"
fingerprint: "${BCK_KEY}"
EOF

  # CREATE pkg(8) KEYS 3/3
  __m "cat << EOF > ${ARG_MNTD}/usr/share/keys/pkgbase-15/trusted/${AWS_NME} (...)"
  cat << EOF > "${ARG_MNTD}/usr/share/keys/pkgbase-15/trusted/${AWS_NME}"
function: "sha256"
fingerprint: "${AWS_KEY}"
EOF

  # CHECK pkg(8) KEYS CREATED SUCCESSFULLY
  if [ ${?} -ne 0 ]
  then
    echo "NOPE: can not create pkg(8) keys"
    __verimg_clean
    exit 1
  fi

  # CREATE /etc and /boot DIRS
  __m "mkdir -p ${ARG_MNTD}/etc ${ARG_MNTD}/boot"
  if ! mkdir -p "${ARG_MNTD}/etc" "${ARG_MNTD}/boot" 2> /dev/null
  then
    echo "NOPE: can not create /boot OR /etc DIRS"
    __verimg_clean
    exit 1
  fi

  # SET BASIC CONFIGS - DNS
  __m "echo nameserver 1.1.1.1 > ${ARG_MNTD}/etc/resolv.conf"
  echo nameserver 1.1.1.1 > "${ARG_MNTD}/etc/resolv.conf"

  # SET BASIC CONFIGS - fstab(5)
  __m "cat << EOF > ${ARG_MNTD}/etc/fstab (...)"
  cat << EOF > "${ARG_MNTD}/etc/fstab"
/dev/gpt/swap0  none  swap  sw,failok  0 0
EOF

  # SET BASIC CONFIGS - loader(8)
  __m "cat << EOF > ${ARG_MNTD}/boot/loader.conf (...)"
  cat << EOF > "${ARG_MNTD}/boot/loader.conf"
zfs_load=YES
kern.geom.label.disk_ident.enable=0
EOF

  # SET BASIC CONFIGS - rc.conf(5)
  __m "cat << EOF > ${ARG_MNTD}/etc/rc.conf (...)"
  cat << EOF > "${ARG_MNTD}/etc/rc.conf"
  ifconfig_DEFAULT="DHCP"
  hostname="verimg"
  zfs_enable=YES
  sshd_enable=YES
EOF

  # CHECK CONFIGS EXIT STATUS
  if [ ${?} -ne 0 ]
  then
    echo "NOPE: can not populate configs"
    __verimg_clean
    exit 1
  fi

  # UPDATE pkg(8) REPOS
  __m "pkg --rootdir ${ARG_MNTD} --repo-conf-dir /usr/obj/repos -o IGNORE_OSVERSION=yes update"
  if ! pkg --rootdir "${ARG_MNTD}" --repo-conf-dir /usr/obj/repos -o IGNORE_OSVERSION=yes \
         update 2> /dev/null
  then
    echo "NOPE: can not update pkg(8) repos"
    __verimg_clean
    exit 1
  fi

  # MOUNT devfs(5) FILESYSTEM INSIDE CHROOT BECAUSE pkg(8) NEEDS /dev/null TO WORK
  mkdir -p                  "${ARG_MNTD}/dev"
  __m "mount -t devfs devfs '${ARG_MNTD}/dev'"
  if ! mount -t devfs devfs "${ARG_MNTD}/dev" 2> /dev/null
  then
    echo "NOPE: can not mount devfs(5) inside '${ARG_MNTD}' dir"
    __verimg_clean
    exit 1
  fi

  echo "# mount -p | grep -v zfs | column -t"
          mount -p | grep -v zfs | column -t

  # PREPARE POTENTIAL CUSTOM KERNEL(s) LIST FOR pkg(8) TO INSTALL
  if [ "${ARG_KERN}" != "GENERIC" ]
  then
    CUSTOM_KERNELS_LIST=$( echo "${ARG_KERN}" | tr ':' ' ' | tr 'A-Z' 'a-z' )
    for I in ${CUSTOM_KERNELS_LIST}
    do
      CUSTOM_KERNELS="${CUSTOM_KERNELS} FreeBSD-kernel-${I} FreeBSD-kernel-${I}-dbg"
    done
  fi

  # INSTALL PKGBASE FreeBSD-set-base SET
  __m "pkg --rootdir ${ARG_MNTD} --repo-conf-dir /usr/obj/repos -o IGNORE_OSVERSION=yes install -r FreeBSD-base -U -y FreeBSD-set-base ${CUSTOM_KERNELS}"
  if ! pkg --rootdir "${ARG_MNTD}" --repo-conf-dir /usr/obj/repos -o IGNORE_OSVERSION=yes \
         install -r FreeBSD-base -U -y FreeBSD-set-base ${CUSTOM_KERNELS} 2> /dev/null
  then
    echo "NOPE: can not install 'FreeBSD-set-base' set"
    __verimg_clean
    exit 1
  fi

  # CREATE TARGET pkg(8) REPOS DIR IN CHROOT
  __m "mkdir -p ${ARG_MNTD}/usr/local/etc/pkg/repos"
  if ! mkdir -p "${ARG_MNTD}/usr/local/etc/pkg/repos" 2> /dev/null
  then
    echo "NOPE: can not create '${ARG_MNTD}/usr/local/etc/pkg/repos' dir"
    __verimg_clean
    exit 1
  fi

  # CHECK WHICH pkg(8) BRANCH WE WANT
  if [ "${ARG_BRCH}" != "quarterly" ]
  then
    # SWITCH FROM 'quarterly' TO 'latest' FOR pkg(8) BRANCH
    __m "sed s/quarterly/${ARG_BRCH}/g ${ARG_MNTD}/etc/pkg/FreeBSD.conf ${ARG_MNTD}/usr/local/etc/pkg/repos/FreeBSD.conf"
    if ! sed s/quarterly/${ARG_BRCH}/g "${ARG_MNTD}/etc/pkg/FreeBSD.conf" \
           > "${ARG_MNTD}/usr/local/etc/pkg/repos/FreeBSD.conf" 2> /dev/null
    then
      echo "NOPE: can not set '${ARG_BRCH}' pkg(8) branch"
      __verimg_clean
      exit 1
    fi
  fi

  # ENABLE PKGBASE IN pkg(8)
  __m "echo 'FreeBSD-base: { enabled: yes }' >> ${ARG_MNTD}/usr/local/etc/pkg/repos/FreeBSD.conf"
  if ! echo 'FreeBSD-base: { enabled: yes }' >> "${ARG_MNTD}/usr/local/etc/pkg/repos/FreeBSD.conf" 2> /dev/null
  then
    echo "NOPE: can not enable PKGBASE in pkg(8) '${ARG_MNTD}/usr/local/etc/pkg/repos/FreeBSD.conf' config"
    __verimg_clean
    exit 1
  fi

  # UPDATE AND BOOTSTRAP pkg(1) IN CHROOT
  __m "chroot '${ARG_MNTD}' env ASSUME_ALWAYS_YES=yes pkg update"
  if ! chroot "${ARG_MNTD}" env ASSUME_ALWAYS_YES=yes pkg update 2> /dev/null
  then
    echo "NOPE: can not update pkg(8) in chroot dir"
    __verimg_clean
    exit 1
  fi

  # INSTALL REQUIRED pkg(8) PACKAGES
  __m "chroot '${ARG_MNTD}' env ASSUME_ALWAYS_YES=yes pkg install -y $( echo ${ARG_INST} | tr ':' ' ' )"
  if ! chroot "${ARG_MNTD}" env ASSUME_ALWAYS_YES=yes pkg install -y $( echo ${ARG_INST} | tr ':' ' ' ) 2> /dev/null
  then
    echo "NOPE: can not install specified pkg(8) packages"
    __verimg_clean
    exit 1
  fi

  # UNMOUNT devfs(5) FILESYSTEM FROM CHROOT
  __m "umount -f '${ARG_MNTD}/dev'"
  if ! umount -f "${ARG_MNTD}/dev" 2> /dev/null
  then
    echo "NOPE: can not unmount devfs(5) from '${ARG_MNTD}' dir"
    __verimg_clean
    exit 1
  fi

  # SET bootfs ZFS POOL PROPERTY IF IN 'img' TYPE AND EXPLORT ZFS POOL
  if [ "${ARG_TYPE}" = "img" ]
  then
    __m "zpool set bootfs=${ARG_POOL}/ROOT/default ${ARG_POOL}"
    if ! zpool set bootfs="${ARG_POOL}/ROOT/default" "${ARG_POOL}" 2> /dev/null
    then
      echo "NOPE: can not setup 'bootfs' ZFS pool property"
      __verimg_clean
      exit 1
    fi

    # EXPORT ZFS POOL
    __m "zpool export ${ARG_POOL}"
    if ! zpool export "${ARG_POOL}" 2> /dev/null
    then
      echo "NOPE: can not export '${ARG_POOL}' ZFS pool"
      __verimg_clean
      exit 1
    fi

    # UNMAP md(4) DEVICE WHEN IN 'img' TYPE
    if [ "${ARG_TYPE}" = "img" ]
    then

      # UNMAP md(4) DEVICE
      __m "mdconfig -d -u /dev/${DEVICE}"
      if ! mdconfig -d -u "/dev/${DEVICE}" 2> /dev/null
      then
        echo "NOPE: can not unmap md(4) device"
        __verimg_clean
        exit 1
      fi

    fi
  fi

  }
# FUNCTION TO SETUP FreeBSD (end)

# FUNCTION TO CHECK THINGS BEFORE MAKING ACTUAL WORK (begin)
__verimg_check() {

  # CHECK IF DISK IMAGE ALREADY EXISTS
  if [ -f "${ARG_FILE}" ]
  then
    echo "NOPE: image '${ARG_FILE}' already exists"
    echo "INFO: you can remove it with following command:"
    echo "INFO:   # rm ${ARG_FILE}"
    EXIT=1
  fi

  # CHECK ZFS POOL NAME IS NOT IN USE IN SYSTEM
  while read POOL
  do
    if [ "${POOL}" = "${ARG_POOL}" ]
    then
      echo "NOPE: ZFS pool '${ARG_POOL}' already exists in the system"
      echo "INFO: export ZFS '${ARG_POOL}' pool with this command:"
      echo "INFO:   # zpool export -f ${ARG_POOL}"
      echo "INFO: ... or use different ZFS pool name then '${ARG_POOL}' one"
      EXIT=1
    fi
  done << EOF
  $( zpool list -H -o name 2> /dev/null)
EOF

  # CHECK IF DISK IMAGE IS ALREADY MAPPED WITH md(4) DRIVER
  ARG_FILE_PATH="$( pwd )/${ARG_FILE}"
  while read NAME TYPE SIZE FILENAME GARBAGE
  do
    if [ "${ARG_FILE_PATH}" = "${FILENAME}" ]
    then
      if ! mdconfig -d -u /dev/${NAME} 2> /dev/null
      then
        echo "NOPE: can not unmap '${ARG_FILE}' from '/dev/${NAME}' place"
        echo "INFO: you can use following command to list mapped md(4) devices"
        echo "INFO:   # mdconfig -l -v"
        echo "INFO: probably ZFS 'ARG_POOL' pool is not exported and blocks it"
        EXIT=1
      fi
    fi
  done << EOF
  $( mdconfig -l -v 2> /dev/null)
EOF

  if [ "${EXIT}" = "1" ]
  then
    __verimg_clean
    exit 1
  fi

  }
# FUNCTION TO CHECK THINGS BEFORE MAKING ACTUAL WORK (end)

# FUNCTION TO CREATE DISK IMAGE (begin)
__verimg_image() {

  # CREATE DISK IMAGE
  __m "truncate -s ${ARG_SIZE} ${ARG_FILE}"
  if ! truncate -s "${ARG_SIZE}" "${ARG_FILE}" 2> /dev/null
  then
    echo "NOPE: truncate(1) is not able to create '${ARG_FILE}' file."
    __verimg_clean
    exit 1
  fi

  # MAP DISK IMAGE WITH md(4) DRIVER
  __m "mdconfig -a -t vnode -f ${ARG_FILE}"
  DEVICE=$( mdconfig -a -t vnode -f "${ARG_FILE}" )
  if ! echo "${DEVICE}" | grep -q -E '^md[0-9]+$' 2> /dev/null
  then
    echo "NOPE: can not map '${ARG_FILE}' file with md(4) driver."
    __verimg_clean
    exit 1
  fi

  # CREATE GPT PARTITION SCHEME AND PARTITIONS
  __m "gpart create/add/bootcode ... ${DEVICE}"
  gpart create -s GPT                                   ${DEVICE}
  gpart add -a 4k -s 512K -t freebsd-boot -l gptboot0   ${DEVICE}
  gpart add -a 4k -s 40M  -t efi          -l efiboot0   ${DEVICE}
  gpart add -a 4k -s 1G   -t freebsd-swap -l swap0      ${DEVICE}
  gpart add -a 4k -s 8G   -t freebsd-zfs  -l zfs0       ${DEVICE}
  gpart bootcode -b /boot/pmbr -p /boot/gptzfsboot -i 1 ${DEVICE}

  # CHECK GPART EXIT STATUS
  if [ ${?} -ne 0 ]
  then
    echo "NOPE: can not create gpart(8) partitions"
    __verimg_clean
    exit 1
  fi

  # CREATE FAT32 FILESYSTEM FOR UEFI PARTITION
  __m "newfs_msdos -F 32 -c 1 /dev/${DEVICE}p2"
  if ! newfs_msdos -F 32 -c 1 "/dev/${DEVICE}p2" 2> /dev/null
  then
    echo "NOPE: can not create FAT32 filesystem for UEFI partition"
    __verimg_clean
    exit 1
  fi

  # CREATE DIRECTORY FOR UEFI MOUNT
  __m "mkdir -p ${ARG_MNTD}/efi"
  if ! mkdir -p "${ARG_MNTD}/efi" 2> /dev/null
  then
    echo "NOPE: can not create UEFI dir."
    __verimg_clean
    exit 1
  fi

  # MOUNT UEFI PARTITION
  __m "mount_msdosfs /dev/${DEVICE}p2 ${ARG_MNTD}/efi"
  if ! mount_msdosfs "/dev/${DEVICE}p2" "${ARG_MNTD}/efi" 2> /dev/null
  then
    echo "NOPE: can not mount UEFI partition"
    __verimg_clean
    exit 1
  fi

  # CREATE UEFI DIRS
  __m "mkdir -p ${ARG_MNTD}/efi/EFI/BOOT"
  if ! mkdir -p "${ARG_MNTD}/efi/EFI/BOOT" 2> /dev/null
  then
    echo "NOPE: can not create UEFI dirs"
    __verimg_clean
    exit 1
  fi

  # INSTALL FreeBSD loader.efi INTO UEFI PARTITION
  __m "cp /boot/loader.efi ${ARG_MNTD}/efi/EFI/BOOT/bootx64.efi"
  if ! cp /boot/loader.efi "${ARG_MNTD}/efi/EFI/BOOT/bootx64.efi" 2> /dev/null
  then
    echo "NOPE: can not install 'loader.efi' into UEFI partition"
    __verimg_clean
    exit 1
  fi

  # UNMOUNT UEFI PARTITION
  __m "umount -f ${ARG_MNTD}/efi"
  umount -f "${ARG_MNTD}/efi" 2> /dev/null

  # CREATE ZFS POOL IF IN 'img' TYPE
  if [ "${ARG_TYPE}" = "img" ]
  then

    # CREATE ZFS POOL
    __m "zpool create -R ${ARG_MNTD} -O compress=lz4 -O atime=off -m none -f ${ARG_POOL} ${DEVICE}p4"
    if ! zpool create -R "${ARG_MNTD}" -O compress=lz4 -O atime=off -m none -f ${ARG_POOL} "${DEVICE}p4" 2> /dev/null
    then
      echo "NOPE: can not create ZFS 'sys' pool"
      __verimg_clean
      exit 1
    fi

    # CREATE ZFS DATASETS
    __m "zfs create ... ${ARG_POOL}"
    zfs create -o mountpoint=none                          ${ARG_POOL}/ROOT
    zfs create -o mountpoint=/                             ${ARG_POOL}/ROOT/default
    zfs create -o mountpoint=/home                         ${ARG_POOL}/home
    zfs create -o mountpoint=/tmp -o exec=on -o setuid=off ${ARG_POOL}/tmp
    zfs create -o mountpoint=/usr -o canmount=off          ${ARG_POOL}/usr
    zfs create -o setuid=off                               ${ARG_POOL}/usr/ports
    zfs create                                             ${ARG_POOL}/usr/src
    zfs create -o mountpoint=/var -o canmount=off          ${ARG_POOL}/var
    zfs create -o exec=off -o setuid=off                   ${ARG_POOL}/var/audit
    zfs create -o exec=off -o setuid=off                   ${ARG_POOL}/var/crash
    zfs create -o exec=off -o setuid=off                   ${ARG_POOL}/var/log
    zfs create -o atime=on                                 ${ARG_POOL}/var/mail
    zfs create -o setuid=off                               ${ARG_POOL}/var/tmp

    # CHECK ZFS CREATE EXIT STATUS
    if [ ${?} -ne 0 ]
    then
      echo "NOPE: can not create ZFS datasets"
      __verimg_clean
      exit 1
    fi

  fi

  }
# FUNCTION TO CREATE DISK IMAGE (end)

# FUNCTION TO PRINT STARTUP VALUES (begin)
__verimg_print() {

  # PRINT STARTUP VALUES
  echo "INFO: options that will be used"
  echo "  ARG_MODE: ${ARG_MODE}"
  echo "  ARG_TYPE: ${ARG_TYPE}"
  echo "  ARG_FILE: ${ARG_FILE}"
  echo "  ARG_SIZE: ${ARG_SIZE}"
  echo "  ARG_VERS: ${ARG_VERS}"
  echo "  ARG_INST: ${ARG_INST}"
  echo "  ARG_MNTD: ${ARG_MNTD}"
  echo "  ARG_SRCD: ${ARG_SRCD}"
  echo "  ARG_KERN: ${ARG_KERN}"
  echo "  ARG_POOL: ${ARG_POOL}"
  echo "  ARG_REPO: ${ARG_REPO}"
  echo "  ARG_BRCH: ${ARG_BRCH}"
  echo

  }
# FUNCTION TO PRINT STARTUP VALUES (end)

# DISPLAY VERSION
case "${1}" in
  (--version|-version|version)
    echo
    echo "verimg 0.3 2026/04/24"
    echo
    exit 0
    ;;
esac

# DISPLAY HELP
case "${1}" in
  (-h|--help|-help|help)
    __usage
    ;;
esac

# OBTAIN ARGUMENTS FOR OPTIONS
while getopts M:t:f:s:S:r:i:m:R:p:k:b:n ARG
do
  case "${ARG}" in
    (M) ARG_MODE="${OPTARG}"                                                 ;;
    (t) ARG_TYPE="${OPTARG}"                                                 ;;
    (f) ARG_FILE="${OPTARG}"                                                 ;;
    (s) ARG_SIZE="${OPTARG}"                                                 ;;
    (r) ARG_VERS="${OPTARG}"                                                 ;;
    (i) ARG_INST="${OPTARG}"                                                 ;;
    (m) ARG_MNTD="${OPTARG}"                                                 ;;
    (S) ARG_SRCD="${OPTARG}"
        ARG_REPO="/usr/obj/${ARG_SRCD}/repo/FreeBSD:15:$( uname -m )/latest" ;;
    (R) ARG_REPO="${OPTARG}"                                                 ;;
    (k) ARG_KERN="GENERIC:${OPTARG}"                                         ;;
    (s) ARG_POOL="${OPTARG}"                                                 ;;
    (b) ARG_BRCH="${OPTARG}"                                                 ;;
    (n) ARG_NDRY="yes"                                                       ;;
    (*) __usage                                                              ;;
  esac
done

case "${ARG_TYPE}" in
  (mnt)
    ARG_FILE="-"
    ARG_SIZE="-"
    ;;
esac

# PRINT STARTUP VALUES
__verimg_print

# EXIT IF DRY RUN DEFINED
if [ "${ARG_NDRY}" = "yes" ]
then
  exit 0
fi

# CHECK NEEDSD THINGS BEFORE DOINT ACTUAL WORK
__verimg_check

# CREATE/PREPARE DISK IMAGE IN 'img' MODE
case "${ARG_TYPE}" in
  (img) __verimg_image ;;
esac

# DO WHAT IS NEEDED IN SPECIFIED MODE
case "${ARG_MODE}" in

  (fetch:build:setup)
    __verimg_fetch
    __verimg_build
    __verimg_setup
    ;;

  (build:setup)
    __verimg_build
    __verimg_setup
    ;;

  (setup)
    __verimg_setup
    ;;

esac
